# Generated by Django 5.2.3 on 2025-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('pages_count', models.PositiveIntegerField()),
                ('keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('passage', models.TextField()),
                ('region_id', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=200)),
                ('page', models.PositiveIntegerField()),
            ],
        ),
    ]
